server:
  port: ${PORT:8080}
spring:
  application:
    name: trustline

  flyway:
    enabled: true
    baseline-on-migrate: true
    connect-retries: 3
    validate-on-migrate: true

  datasource:
    url: jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require&reWriteBatchedInserts=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
      idle-timeout: 300000
      max-lifetime: 1200000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 15000

  jpa:
    show-sql: false
    properties:
      hibernate:
        ddl-auto: create
        format_sql: true

jwt:
  signin:
    key: ${JWT_KEY}
    secret: ${JWT_SECRET}

firebase:
  config:
    location: ${FIREBASE_CONFIG_LOCATION}

cloudinary:
  cloud-name: ddj3hjr57
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_SERET}

email:
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
  mailerSend:
    api-key: ${MAIL_SENDER_API_KEY}
  resend:
    api-key: ${RESEND_API_KEY}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
