name: Deploy to Dev (Render)

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render deploy
        run: |
          if [ -z "${{ secrets.RENDER_DEPLOY_HOOK }}" ]; then
            echo "RENDER_DEPLOY_HOOK is NOT set"
            exit 1
          else
            echo "RENDER_DEPLOY_HOOK is set"
          fi
